---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Brandon Johnson"
keywords:    "SinglePaged, jekyll, template, github, single page, Brandon, Brandon Johnson, taylus, legacy.codes"
description: "The personal homepage for Brandon Johnson, software developer."
source_link: "https://github.com/taylus/SinglePaged"
favicon:     "favicon.ico"
touch_icon:
google_analytics_key: ## (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#173773'
  green:     '#9bcf2f'
  purple:    '#2d1a77'
  orange:    '#fab125'
  turquoise: '#0c6b61'
  red:       '#960f23'

kramdown:
  auto_ids:  false

